Repository TechLabs-Berlin/wt21-the-noise-enricher, pull requests merged in 2022-01, with the labels that each got.

#8 Express server and HEROKU deployment
  README.md
  node_app/client/app.js
  node_app/client/index.css
  node_app/client/index.html
  node_app/client/index.js
  node_app/server/app.js
  node_app/server/package-lock.json
  node_app/server/package.json
  package.json
Labels: backend

#10 clean up old files, added Jupyter Notebooks for creating neural network for classifying music genres
  first_nn.ipynb
  python_app/data_preparation_classifier.ipynb
  python_app/dataset_files_test.csv
  python_app/dataset_files_train.csv
  python_app/nn_genre_classification_application.ipynb
  python_app/nn_genre_classification_model.ipynb
Labels: AI

#12 Media query imlementation -1200 -900 -700
  node_app/client/index.css
  node_app/client/index.html
Labels: frontend

#18 Background improvement + Overall aesthetics
  node_app/client/PRO.html
  node_app/client/about.html
  node_app/client/background.html
  node_app/client/css/PRO.css
  node_app/client/css/about.css
  node_app/client/css/background.css
  node_app/client/css/index.css
  node_app/client/index.html
  node_app/client/js/background.js
Labels: frontend

#19 update of font and color pallet based of Figma's direction
  node_app/client/PRO.html
  node_app/client/about.html
  node_app/client/content/favicon.png
  node_app/client/css/PRO.css
  node_app/client/css/about.css
  node_app/client/css/background.css
  node_app/client/css/index.css
  node_app/client/index.html
Labels: frontend, UX

#21 Templating routing
  .gitignore
  node_app/client/PRO.html
  node_app/client/about.html
  node_app/client/background.html
  node_app/client/css/generate.css
  node_app/client/index.html
  node_app/client/public/content/animatedWaves.gif
  node_app/client/public/content/favicon.png
  node_app/client/public/content/noun-drum-135575.svg
  node_app/client/public/content/noun-guitar-135543.svg
  node_app/client/public/content/noun-harp-135545.svg
  node_app/client/public/content/noun-piano-135571.svg
  node_app/client/public/content/noun-tuba-135555.svg
  node_app/client/public/content/waveform.png
  node_app/client/public/css/PRO.css
  node_app/client/public/css/about.css
  node_app/client/public/css/background.css
  node_app/client/public/css/generate.css
  node_app/client/public/css/index.css
  node_app/client/public/js/background.js
  node_app/client/public/js/draw_spectrogram.js
  node_app/client/public/js/index.js
  node_app/client/views/generate/generate_pro.ejs
  node_app/client/views/generate/index.ejs
  node_app/client/views/generate/results.ejs
  node_app/client/views/generate/spectrogram.ejs
  node_app/client/views/home.ejs
  node_app/client/views/layouts/boilerplate.ejs
  node_app/client/views/partials/background_animation.ejs
  node_app/client/views/partials/footer.ejs
  node_app/client/views/partials/navbar.ejs
  node_app/server/app.js
  node_app/server/controllers/google.js
  node_app/server/package-lock.json
  node_app/server/package.json
  node_app/server/routes/generate.js
Labels: frontend, backend

#20 UI resources added to UX directory
  ux/ui/favicon.png
  ux/ui/home-1.png
  ux/ui/home-2.png
  ux/ui/logo.png
  ux/ui/palette.scss
  ux/ui/the-noise-enricher.fig
Labels: frontend, UX

#22 Ai backend frontend
  node_app/client/views/generate/results.ejs
  node_app/server/routes/generate.js
  python_app/dummy_transformer.py
  python_app/flask_app.py
  python_app/test_heroku.py
  requirements.txt
  runtime.txt
Labels: backend, AI

#37 Embrace the noise
  Aptfile
  node_app/client/views/generate/results.ejs
  node_app/server/controllers/google.js
  node_app/server/controllers/run-python.js
  node_app/server/routes/generate.js
  python_app/call_generate_audio.py
  python_app/enricher_models.py
  python_app/input_preprocessing.py
  python_app/sound_generator.py
  requirements.txt
Labels: backend, AI

#39 Loading page
  node_app/client/views/generate/spectrogram.ejs
  node_app/client/views/layouts/boilerplate.ejs
  node_app/server/controllers/generate-audio.js
  node_app/server/routes/generate.js
  node_app/server/utils/catchAsync.js
Labels: backend

#43 Fix bug uploaded files
  Procfile
  node_app/server/controllers/generate-audio.js
  node_app/server/routes/generate.js
Labels: backend

#38 JS integration, new small menu, background behavior
  node_app/client/public/css/PRO.css
  node_app/client/public/css/background.css
  node_app/client/public/css/index.css
  node_app/client/public/js/background.js
  node_app/client/public/js/index.js
  node_app/client/public/js/toBeDefined.js
  node_app/client/views/generate/about.ejs
  node_app/client/views/generate/generate_pro.ejs
  node_app/client/views/index.ejs
  node_app/client/views/partials/navbar.ejs
Labels: frontend

#47 Reduce pressure on the server
  node_app/client/views/generate/results.ejs
  node_app/server/app.js
  node_app/server/controllers/generate-audio.js
  node_app/server/controllers/run-python.js
  node_app/server/package-lock.json
  node_app/server/package.json
  node_app/server/routes/generate.js
  node_app/server/utils/utils.js
Labels: backend

#48 add alert message if file is too big
  node_app/client/views/layouts/boilerplate.ejs
  node_app/client/views/partials/flash.ejs
  node_app/server/app.js
  node_app/server/controllers/generate-audio.js
  node_app/server/package-lock.json
  node_app/server/package.json
  node_app/server/routes/generate.js
Labels: frontend, backend

#50 add different sound styles support
  node_app/server/controllers/generate-audio.js
  node_app/server/controllers/run-python.js
  python_app/call_generate_audio.py
Labels: frontend, backend, AI
