Repository TechLabs-Berlin/wt21-the-noise-enricher, pull requests merged in 2022-02, with the labels that each got.

#56 add deployment description
  README.md
  docs/build_heroku.png
  docs/buildpacks.png
Labels: documentation

#53 new Landing page
  node_app/client/public/css/PRO.css
  node_app/client/public/css/about.css
  node_app/client/public/css/background.css
  node_app/client/public/css/index.css
  node_app/client/public/js/index.js
  node_app/client/views/generate/about.ejs
  node_app/client/views/generate/generate_pro.ejs
  node_app/client/views/index.ejs
  node_app/server/package-lock.json
  node_app/server/package.json
Labels: frontend

#58 audio input
  node_app/client/content/free-microphone-icon-342-thumb.png
  node_app/client/public/css/PRO.css
  node_app/client/public/css/button.css
  node_app/client/public/css/index.css
  node_app/client/public/js/audio_recording/main.js
  node_app/client/public/js/audio_recording/recorder.js
  node_app/client/public/js/audio_recording/recorderWorker.js
  node_app/client/public/js/index.js
  node_app/client/views/generate/generate_pro.ejs
  node_app/client/views/index.ejs
  node_app/client/views/partials/button.html
Labels: frontend, backend

#59 spectrogram final edits
  node_app/client/content/loading.gif
  node_app/client/content/thumb-down.png
  node_app/client/content/thumb-up.png
  node_app/client/public/css/background.css
  node_app/client/public/css/index.css
  node_app/client/public/css/results.css
  node_app/client/public/css/spectrogram.css
  node_app/client/public/js/audio_recording/main.js
  node_app/client/public/js/audio_recording/recorder.js
  node_app/client/public/js/audio_recording/recorderWorker.js
  node_app/client/public/js/draw_spectrogram.js
  node_app/client/views/generate/generate_pro.ejs
  node_app/client/views/generate/results.ejs
  node_app/client/views/generate/spectrogram.ejs
  node_app/client/views/index.ejs
  node_app/client/views/partials/button.html
  node_app/runtime.txt
  node_app/server/app.js
  node_app/server/controllers/generate-audio.js
  node_app/server/routes/generate.js
Labels: frontend, UX

#62 Steps to run the prototype locally
  README.md
  node_app/server/package-lock.json
  node_app/server/package.json
  package.json
  runtime.txt
Labels: documentation, backend

#63 add team and dependencies
  README.md
Labels: documentation

#60 Polishing of code and added explanation text
  node_app/client/public/content/someaudio.wav
  node_app/client/public/css/PRO.css
  node_app/client/public/css/about.css
  node_app/client/public/css/index.css
  node_app/client/public/css/spectrogram.css
  node_app/client/public/js/draw_spectrogram.js
  node_app/client/public/js/index.js
  node_app/client/public/js/navbar.js
  node_app/client/views/generate/about.ejs
  node_app/client/views/generate/generate_pro.ejs
  node_app/client/views/generate/spectrogram.ejs
  node_app/client/views/index.ejs
  node_app/client/views/partials/navbar.ejs
  node_app/server/app.js
Labels: frontend, backend

#65 add team links
  README.md
Labels: documentation

#67 add WD uml components diagram
  docs/web_app_uml_components.png
  docs/web_app_uml_components.puml
Labels: documentation, frontend, backend

#68 add AI images
  docs/CNN.png
  docs/spectrograms_comparison.jpg
Labels: documentation, AI

#69 add ux blog post image
  docs/persona-two.png
Labels: documentation, UX

#72 update team links
  README.md
Labels: documentation

#73 user testing pdf added
  ux/the-noise-enricher-user-testing.pdf
Labels: documentation, UX
